const Surface = require("./surface")

const plateau = new Surface(5,5)
const rover = plateau.addRover(1, 2, "N")
const rover2 = plateau.addRover(3,3, "E")
rover.sendSignal("LMLMLMLMM", plateau)
console.log(rover.pingLocation())
rover2.sendSignal("MMRMMRMRRM", plateau)
console.log(rover2.pingLocation())
console.log(plateau.getGrid())
